name: cosmopipe
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=h69a702a_13
  - astropy=6.0.0=py311h1f0f07a_0
  - astropy-iers-data=0.2023.12.4.0.30.20=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - binutils=2.40=hdd6e379_0
  - binutils_impl_linux-64=2.40=hf600244_0
  - binutils_linux-64=2.40=hbdbef99_2
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py311hb755f60_1
  - brotlipy=0.7.0=py311h459d7ec_1006
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.23.0=hd590300_0
  - c-compiler=1.7.0=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cairo=1.16.0=ha61ee94_1014
  - camb=1.5.2=py311hbc92942_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py311hb3a22ac_0
  - cfitsio=4.2.0=hd9d235c_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - compilers=1.7.0=ha770c72_0
  - contourpy=1.2.0=py311h9547e67_0
  - cosmosis=2.5.1=py311h615265c_0
  - cosmosis-build-standard-library=1.2=py311h8783aee_3
  - cryptography=41.0.7=py311hcb13ee4_1
  - curl=8.1.2=h409715c_0
  - cxx-compiler=1.7.0=h00ab1b0_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dulwich=0.21.6=py311h459d7ec_2
  - dynesty=2.1.2=pyhd8ed1ab_0
  - emcee=3.1.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fast-pt=3.1.1=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hc118613_108
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.46.0=py311h459d7ec_0
  - fortran-compiler=1.7.0=heb67821_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - future=0.18.3=pyhd8ed1ab_0
  - gcc=12.3.0=h8d2909c_2
  - gcc_impl_linux-64=12.3.0=he2b93b0_3
  - gcc_linux-64=12.3.0=h76fc315_2
  - gettext=0.21.1=h27087fc_0
  - gfortran=12.3.0=h499e0f7_2
  - gfortran_impl_linux-64=12.3.0=hfcedea8_3
  - gfortran_linux-64=12.3.0=h7fe76b4_2
  - git=2.42.0=pl5321h86e50cf_0
  - gmp=6.3.0=h59595ed_0
  - gmpy2=2.1.2=py311h6a5fa03_1
  - graphite2=1.3.13=h58526e2_1001
  - gxx=12.3.0=h8d2909c_2
  - gxx_impl_linux-64=12.3.0=he2b93b0_3
  - gxx_linux-64=12.3.0=h8a814eb_2
  - harfbuzz=6.0.0=h8e241bc_0
  - icu=70.1=h27087fc_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.0=pyha770c72_0
  - importlib-resources=6.1.1=pyhd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=4.18.0=he073ed8_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py311h9547e67_1
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=20_linux64_openblas
  - libcurl=8.1.2=h409715c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=12.3.0=h8bca6fd_103
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_3
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=20_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopenlibm4=0.8.1=hd590300_1
  - libpng=1.6.39=h753d276_0
  - libsanitizer=12.3.0=h0f45ef3_3
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=12.3.0=h8bca6fd_103
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=8.0.1=hc9558a2_0
  - make=4.3=hd18ef5c_1
  - matplotlib-base=3.8.2=py311h54ef318_0
  - minuit2_standalone=6.22.06=h9c3ff4c_100
  - mock=5.1.0=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_0
  - mpi=1.0=openmpi
  - mpi4py=3.1.5=py311h4267d7f_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nautilus-sampler=0.7.2=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - openjpeg=2.5.0=hfec8fc6_2
  - openlibm=0.8.1=hd590300_1
  - openmp=8.0.1=0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.2.0=hd590300_1
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.3=py311h320fe9a_0
  - pango=1.50.14=hd33c08f_0
  - patsy=0.5.4=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=4_hd590300_perl5
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - pooch=1.8.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pybind11=2.11.1=py311h9547e67_2
  - pybind11-global=2.11.1=py311h9547e67_2
  - pycparser=2.21=pyhd8ed1ab_0
  - pyerfa=2.0.1.1=py311h1f0f07a_0
  - pyopenssl=23.3.0=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.3=pyhd8ed1ab_0
  - python=3.11.6=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h459d7ec_1
  - r=4.2=r42hd8ed1ab_1007
  - r-base=4.2.3=ha7d60f8_0
  - r-boot=1.3_28.1=r42hc72bb7e_1
  - r-class=7.3_22=r42h57805ef_1
  - r-cluster=2.1.6=r42h61816a4_0
  - r-codetools=0.2_19=r42hc72bb7e_1
  - r-foreign=0.8_86=r42h57805ef_0
  - r-kernsmooth=2.23_22=r42h13b3f57_0
  - r-lattice=0.22_5=r42h57805ef_0
  - r-mass=7.3_60=r42h57805ef_1
  - r-matrix=1.6_4=r42h316c678_0
  - r-mgcv=1.9_0=r42h316c678_0
  - r-nlme=3.1_164=r42h61816a4_0
  - r-nnet=7.3_19=r42h57805ef_1
  - r-recommended=4.2=r42hd8ed1ab_1006
  - r-remotes=2.4.2.1=r42hc72bb7e_0
  - r-rpart=4.1.21=r42h57805ef_0
  - r-spatial=7.3_17=r42h57805ef_0
  - r-survival=3.5_7=r42h57805ef_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py311hc009520_1
  - scipy=1.11.4=py311h64a7726_0
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - sed=4.8=he412f7d_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - statsmodels=0.14.0=py311h1f0f07a_2
  - sympy=1.12=pypyh9d50eac_103
  - sysroot_linux-64=2.28=he073ed8_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h0c5db8f_5
  - tomli=2.0.1=pyhd8ed1ab_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.1.0=py311h459d7ec_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeus-mcmc=2.5.4=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.0.0
      - annotated-types==0.6.0
      - astropandas==1.2.2
      - astunparse==1.6.3
      - cached-property==1.5.2
      - cachetools==5.3.2
      - chainconsumer==0.34.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - cosmopower==0.1.3
      - cython==3.0.6
      - d2to1==0.2.12.post1
      - decorator==5.1.1
      - deprecation==2.1.0
      - dm-tree==0.1.8
      - fitsio==1.2.1
      - flatbuffers==23.5.26
      - galselect @ git+https://github.com/jlvdb/galselect.git
      - gast==0.4.0
      - google-auth==2.24.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.3
      - gsl==0.0.3
      - h5py==3.10.0
      - healpy==1.16.6
      - hmf==3.4.4
      - halomod==2.1.1
      - hankel==1.2.2
      - colossus==1.3.5
      - dark_emulator==1.1.2
      - jax==0.4.21
      - keras==2.12.0
      - libclang==16.0.6
      - lsstdesc-coord==1.3.0
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - ml-dtypes==0.3.1
      - numpy==1.23.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - palettable==3.3.3
      - pillow==10.1.0
      - protobuf==4.25.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pygments==2.17.2
      - pytest-runner==6.0.1
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rsa==4.9
      - tabeval @ git+https://github.com/jlvdb/tabeval.git
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - tensorflow-probability==0.19.0
      - termcolor==2.4.0
      - toml==0.10.2
      - treecorr==4.2.3
      - werkzeug==3.0.1
      - wget==3.2
      - wrapt==1.14.1
